imports:
    - { resource: config_dev.yml }

parameters:
    product_image_source: '%kernel.root_dir%/../tests/data'
    product_image_path: '%kernel.root_dir%/../tests/data/uploads'

doctrine:
    dbal:
        path: '%kernel.root_dir%/../tests/data/database.db3'

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

twig:
    date:
        format: Y-m-d, H:i:s

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
