imports:
    - { resource: config_dev.yml }

parameters:
    product_image_destination: /tmp/prontopro

doctrine:
    dbal:
        path: '%kernel.root_dir%/../tests/data.db3'

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
