# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    product_persister:
        class: AppBundle\Service\ProductPersister
        arguments: ['@doctrine']

    finder:
        abstract: true
        arguments: ['@doctrine.orm.entity_manager']

    finder.product:
        class: AppBundle\Finder\ProductFinder
        parent: finder

    finder.tag:
        class: AppBundle\Finder\TagFinder
        parent: finder

    vm.create_product:
        class: AppBundle\ViewModel\CreateProduct
        arguments: ['@templating']

    vm.product_list:
        class: AppBundle\ViewModel\ProductList
        arguments: ['@templating']

    app.form.type.tags:
        class: AppBundle\Form\Type\TagsType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags: [{ name: form.type }]
    
    app.twig.thumb_image_ext:
        class: AppBundle\Twig\Extension\ThumbImageExtension
        arguments: ['@vich_uploader.templating.helper.uploader_helper']
        tags: [{ name: twig.extension }]
