# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    finder:
        abstract: true
        arguments: ['@doctrine.orm.entity_manager']

    finder.product:
        class: AppBundle\Finder\ProductFinder
        parent: finder

    finder.tag:
        class: AppBundle\Finder\TagFinder
        parent: finder

    vm:
        abstract: true
        arguments: ['@templating']

    vm.manage_product:
        class: AppBundle\ViewModel\ManageProduct
        parent: vm

    vm.product_list:
        class: AppBundle\ViewModel\ProductList
        parent: vm

    app.form.type.tags:
        class: AppBundle\Form\Type\TagsType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags: [{ name: form.type }]
    
    app.twig.thumb_image_ext:
        class: AppBundle\Twig\Extension\ThumbImageExtension
        arguments: ['%product_thumb_uri%']
        tags: [{ name: twig.extension }]

    app.listener.product_image_upload:
        class: AppBundle\EventListener\ProductImageUploadListener
        arguments: ['%product_thumb_path%', '%product_thumb_width%','%product_thumb_height%']
        tags:
            - { name: kernel.event_listener, event: vich_uploader.post_upload, method: onPostUpload }
            - { name: kernel.event_listener, event: vich_uploader.pre_remove, method: onRemoveUpload }
