# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    product_persister:
        class: AppBundle\Service\ProductPersister
        arguments: ['@doctrine']

    vm.create_product:
        class: AppBundle\ViewModel\CreateProduct
        arguments: ['@templating']

    vm.product_list:
        class: AppBundle\ViewModel\ProductList
        arguments: ['@templating']

    app.form.type.tags:
        class: AppBundle\Form\Type\TagsType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags: [{ name: form.type }]
